# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment
  labels:
    app: kube-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-lab-app
  template:
    metadata:
      labels:
        app: kube-lab-app
    spec:
      containers:
      - name: kube-lab-app
        image: kube-lab-app:v1 # Local image name
        ports:
        - containerPort: 8080 # This must match the EXPOSE in Dockerfile/app